#!/bin/bash
cd `dirname $0`

SOUND_MANAGER=fakeSoundManager
#SOUND_MANAGER=realSoundManager
PARAMS="soundManager=$SOUND_MANAGER"
BROWSER_URL="http://localhost:9393/TestRunner?$PARAMS"

BROWSER=/usr/bin/google-chrome # location for Linux
if [ -e "$BROWSER" ]; then
  $BROWSER "$BROWSER_URL"
else
  open "$BROWSER_URL" # for Mac
fi

PHANTOMJS="/usr/local/bin/phantomjs" # location on Mac
if [ ! -e "$PHANTOMJS" ]; then
  PHANTOMJS="../phantomjs-1.7.0-linux-i686/bin/phantomjs" # location for Linux
fi

# headless
$PHANTOMJS tools/phantom-jasmine/run_jasmine_test.coffee "$BROWSER_URL"
