#!/bin/bash
cd `dirname $0`

SOUND_MANAGER=fakeSoundManager
#SOUND_MANAGER=realSoundManager
PARAMS="soundManager=$SOUND_MANAGER"
BROWSER_URL="http://localhost:8888/www/TestRunner.html?$PARAMS"

# from browser (Mac)
open "$BROWSER_URL"

# from browser (Linux)
google-chrome "$BROWSER_URL"

PHANTOMJS="/usr/local/bin/phantomjs" # location on Mac
if [ -e "$PHANTOMJS" ]; then
  PHANTOMJS="../phantomjs-1.7.0-linux-i686/bin/phantomjs" # location for Linux
fi

# headless
$PHANTOM_JS tools/phantom-jasmine/run_jasmine_test.coffee \
  "www/TestRunner.html?$PARAMS"
