#!/bin/bash
cd `dirname $0`

# from browser
google-chrome www/TestRunner.html

# headless
../phantomjs-1.7.0-linux-i686/bin/phantomjs tools/phantom-jasmine/run_jasmine_test.coffee www/TestRunner.html 
