#!/bin/sh
cd `dirname $0`

make
if [ "$?" != "0" ]; then exit 1; fi

# Mac
open http://localhost:8888/www/segmenter.html

# Ubuntu
google-chrome http://localhost:8888/www/segmenter.html >/dev/null 2>/dev/null &

node tools/web-server.js
