---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: www
  domain: vocabincontext.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: unicorn_nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: unicorn
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: node
    options: {}
  instance_id: i-6ec93110
  image_type: m1.small
  image_id: ami-3b4ff252
  security_groups:
  - vic_production_default
  - vic_production_web
  - vic_production_www
  - vic_production_haproxy
  - vic_production_collectd
  - vic_production_monit
  - vic_production_app
  - vic_production_unicorn_nginx
  - vic_production_db
  - vic_production_postgresql
  - vic_production_postgresql_master
  - vic_production_nginx
  - vic_production_unicorn
  - vic_production_node
  external_host: ec2-23-22-132-79.compute-1.amazonaws.com
  external_ip: 23.22.132.79
  internal_host: ip-10-32-145-87.ec2.internal
  internal_ip: 10.32.145.87
  zone: us-east-1c
  platform: linux
  root_device_type: ebs
- volumes: {}
  static_ips: {}
